server:
  port: 8011
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful
  # ssl:
  #   enabled: true
  #   key-store: keystore.p12
  #   key-store-password: anstnsp
  #   key-store-type: PKCS12
  #   key-alias: spring1
     
spring:
  profiles:
    active: local 

  pid:
    file: process.pid
  jwt:
    secret: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    hikari:
      driver-class-name:  org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop


restTemplate:
  readTimeout: 5000
  connectTimeout: 3000
  maxConnTotal: 50
  maxConnPerRoute: 50
  url: http://172.6.14.99:8099/saveNpdResultData.do